apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook
  annotations:
    cert-manager.io/inject-ca-from: default/webhook-certificate
webhooks:
#  - name: handle.validate.v1.pod
#    failurePolicy: Ignore
#    namespaceSelector:
#      matchExpressions:
#        - key: webhook
#          operator: In
#          values:
#            - enabled
#    clientConfig:
#      service:
#        name: webhook
#        namespace: default
#        path: "/handle-validate-v1-pod"
#    rules:
#      - apiGroups:
#          - ""
#        apiVersions:
#          - v1
#        operations:
#          - CREATE
#        resources:
#          - pods
#    admissionReviewVersions:
#      - v1
#    sideEffects: None
#  - name: validate.v1.pod
#    failurePolicy: Ignore
#    namespaceSelector:
#      matchExpressions:
#        - key: webhook
#          operator: In
#          values:
#            - enabled
#    clientConfig:
#      service:
#        name: webhook
#        namespace: default
#        path: "/validate-v1-pod"
#    rules:
#      - apiGroups:
#          - ""
#        apiVersions:
#          - v1
#        operations:
#          - UPDATE
#        resources:
#          - pods
#    admissionReviewVersions:
#      - v1
#    sideEffects: None
#  - name: handle-mutate-v1-pod
#    failurePolicy: Ignore
#    namespaceSelector:
#      matchExpressions:
#        - key: webhook
#          operator: In
#          values:
#            - enabled
#    clientConfig:
#      service:
#        name: webhook
#        namespace: default
#        path: "/handle-mutate-v1-pod"
#    rules:
#      - apiGroups:
#          - ""
#        apiVersions:
#          - v1
#        operations:
#          - CREATE
#        resources:
#          - pods
#    admissionReviewVersions:
#      - v1
#    sideEffects: None
  - name: mutate.v1.pod
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - key: webhook
          operator: In
          values:
            - enabled
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: /mutate-v1-pod
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - UPDATE
        resources:
          - pods
    admissionReviewVersions:
      - v1
    sideEffects: None
